language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r beenz-springboot2-webservice *
  - mkdir -p deploy
  - mv beenz-springboot2-webservice.zip deploy/beenz-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: beenz-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: beenz-springboot-build
    key: beenz-springboot2-webservice.zip
    bundle_type: zip
    application: beenz-springboot2-webservice

    deployment_group: beenz-springboot2-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - heatarin@gmail.com